name: Static Site Build

on:
  push:

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM dependencies
        shell: bash
        run: npm install
      - name: Generate Chart Data
        run: |
          cd src/ && python faculty_analysis.py
      - name: Build
        run: npm run build
